[workspace]
resolver = "3"
members = ["crates/uvt", "crates/uvt-plot"]

[workspace.package]
edition = "2024"
authors = ["Damien LaRocque <phicoltan@gmail.com"]
repository = "https://github.com/IamPhytan/uvt-rs"

[workspace.dependencies]
uvt = { path = "crates/uvt" }
