[package]
name = "uvt"
description = "Utilities for interacting with Uncrewed Vehicle Trajectory (UVT) files."
version = "0.1.0"
edition = { workspace = true }

[dependencies]
quaternion = "2.0.0"
rosbag = "0.6.3"
vtkio = "0.6.3"
